name: Dev release and publish Python distributions to PyPI. New gRPC generator

on:
  push:
    branches:
      - dev-version-*
    paths-ignore:
      - README.md

jobs:
  build-n-publish:
    name: Build and Python distributions to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get package version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package_info.json
          prop_path: package_version
      - name: Create dev package version
        id: devPostfix
        run: echo "value="${{ steps.version.outputs.prop }}-dev"" >> $GITHUB_OUTPUT
      - name: Set version for current build in package_info.json
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: './package_info.json'
          key: 'package_version'
          value: ${{ steps.devPostfix.outputs.value }}
      - name: Show version
        run: echo ${{ steps.devPostfix.outputs.value }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Build package
        run: |
          pip install -r requirements.txt
          python setup.py generate -s
          python setup.py sdist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/
  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main