name: Build and publish Python distributions to PyPI. New gRPC generator

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - package_info.json

jobs:
  build-n-publish:
    name: Build and Python distributions to PyPI
    uses: th2-net/.github/.github/workflows/compaund-python-grpc-pypi-publication.yml@main
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main